[project]
name = "pyrtlsweeper"
version = "1.0.0"
readme = "README.md"
authors = [{ name = "Edwin Chang" }]
requires-python = ">=3.13"
dependencies = [
    "hatchling>=1.27.0",
    "pyrtl>=0.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
